package output

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/AdmissionVet/admissionvet/internal/policy"
)

const chartYAML = `apiVersion: v2
name: admissionvet-policies
description: OPA/Gatekeeper policies generated by AdmissionVet
type: application
version: 0.1.0
appVersion: "0.1.0"
`

const helmValuesYAML = `# Default values for admissionvet-policies.
# Override enforcement actions per rule here.
enforcement:
  # "deny" blocks the resource, "warn" allows with a warning
  default: deny
`

// WriteHelm writes a Helm chart structure under outputDir/helm/.
func WriteHelm(policies []*policy.GeneratedPolicy, outputDir string) error {
	helmDir := filepath.Join(outputDir, "helm")
	templateDir := filepath.Join(helmDir, "templates")
	ctDir := filepath.Join(templateDir, "constrainttemplates")
	cDir := filepath.Join(templateDir, "constraints")
	npDir := filepath.Join(templateDir, "networkpolicies")

	for _, dir := range []string{ctDir, cDir, npDir} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("creating helm directory %s: %w", dir, err)
		}
	}

	if err := os.WriteFile(filepath.Join(helmDir, "Chart.yaml"), []byte(chartYAML), 0o644); err != nil {
		return fmt.Errorf("writing Chart.yaml: %w", err)
	}
	if err := os.WriteFile(filepath.Join(helmDir, "values.yaml"), []byte(helmValuesYAML), 0o644); err != nil {
		return fmt.Errorf("writing values.yaml: %w", err)
	}

	for _, p := range policies {
		ruleID := strings.ToLower(p.RuleID)

		if p.ConstraintTemplate != "" {
			path := filepath.Join(ctDir, ruleID+"-constrainttemplate.yaml")
			if err := os.WriteFile(path, []byte(p.ConstraintTemplate), 0o644); err != nil {
				return fmt.Errorf("writing CT for %s: %w", p.RuleID, err)
			}
			fmt.Printf("  wrote %s\n", path)
		}

		if p.Constraint != "" {
			path := filepath.Join(cDir, ruleID+"-constraint.yaml")
			if err := os.WriteFile(path, []byte(p.Constraint), 0o644); err != nil {
				return fmt.Errorf("writing Constraint for %s: %w", p.RuleID, err)
			}
			fmt.Printf("  wrote %s\n", path)
		}

		if p.NetworkPolicy != "" {
			path := filepath.Join(npDir, ruleID+"-networkpolicy.yaml")
			if err := os.WriteFile(path, []byte(p.NetworkPolicy), 0o644); err != nil {
				return fmt.Errorf("writing NetworkPolicy for %s: %w", p.RuleID, err)
			}
			fmt.Printf("  wrote %s\n", path)
		}
	}

	fmt.Printf("  wrote %s\n", filepath.Join(helmDir, "Chart.yaml"))
	fmt.Printf("  wrote %s\n", filepath.Join(helmDir, "values.yaml"))
	return nil
}
